### ISSUE TITLE
Namespaces - Wann und wie verwenden?

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/rex_repo_template#1]
In welchem Kontext / warum werden Namespaces verlangt und welche Vorteile haben diese? Wann machen sich diese in der Praxis bemerkbar?

**Comment by skerbis** [comment]
Du hast es in die Readme geschrieben. Bitte dann auch erklären.

**Comment by AWqxKAWERbXo** [comment]
Hä, was soll das denn jetzt als Kommentar? Nur, weil ich die Anforderung aufgenommen und reingeschrieben habe, heißt das nicht, dass ich Ahnung davon haben muss. Deswegen frage ich ja.

**Comment by skerbis** [comment]
sorry , war vielleicht etwas pampig. Denke aber auch dass es hier nicht wirklich erklärt werden muss. Sondern eher in der Doku.

**Comment by AWqxKAWERbXo** [comment]
Ja, passt schon. 

Ich wäre dankbar, wenn's jemand erklärt, sodass ich es verstehe, bisher habe ich nur den Eindruck, dass namespaces den Komplexitätsgrad erhöhen ohne Mehrwert - aber den muss es ja geben, sonst würde man den Weg ja nicht gehen.

**Comment by aeberhard** [comment]
Vielleicht hilft das ja ein wenig weiter.

Die Komplexität wird m.E. nicht erhöht, der Schreibaufwand beim Coden vielleicht :)
Erhöht aber die Lesbarkeit für den Compiler und auch für den Programmierer.

> A namespace is used to avoid conflicting definitions and introduce more flexibility and organization in the code base. Just like directories, namespace can contain a hierarchy know as subnamespaces. PHP uses the backslash as its namespace separator.

https://www.phptutorial.net/php-oop/php-namespace/

Aber die Profis dazu sind @gharlan und @staabm 

Und wichtig: `rexstan` verwenden !!!

**Comment by skerbis** [comment]
zusätzlich dient es zur Vorbereitung auf einen zukünftigen composer workflow

**Comment by AWqxKAWERbXo** [comment]
@skerbis @aeberhard gibt's Tools, die das in bestehenden Repos nachholen, wenn das zukünftig ohnehin gewünscht ist in der Verwendung?

rexstan habe ich schon Mal ausprobiert, aber mir sind 

1. die Fehlermeldungen nicht einsteigerfreundlich genug, 
2. ich werde auch nicht wie auf Slack üblicherweise geraten jede Meldung, die ich nicht verstehe, mit ignore-next-line kennzeichnen (wie absurd!)
3. und ich halte mich wie gewünscht vom Addon-Autor fern.

Wer mir da ein wenig Starthilfe geben mag, die Meldungen besser zu verstehen, der kann sich sicher sein, dass ich das der Community wie sonst auch wieder zurück gebe und irgendwo umsetze.

**Comment by aeberhard** [comment]
@alxndr-w Nein ich denke da wird es keine Tools geben :(

1. Ja, und die FAQ ist noch ausbaufähig, aber genau lesen und googlen hilft da auch
2. in manchen Fällen braucht es wirklich `@phpstan-ignore-next-line` oder `@phpstan-ignore-line`  (https://phpstan.org/user-guide/ignoring-errors)
z.B. `curl_exec()` liefert ab PHP 8.x ein 'CurlHandle' und in vorigen PHP-Versionen eine Resource
Wenn das jetzt PHP7-Kompatibel sein soll dann brauchst Du einen ignore. Ansonsten nicht.
4. verstehe ich nicht :(

Wegen rexstan kannst mich gerne Fragen, da ich grade an einem Addon dran bin (von grundauf mit rexstan entwickelt) und schon viele Fehler in meinem Addon korrigiert bzw. komplett überarbeitet habe :)

Letztendlich geht es bei dem ganzen darum den Code leserlich und wartbar zu programmieren.
Und dass korrekte Werte an Funktionen / Klassen übergeben werden.
Minimiert halt insgesamt die Fehlerquellen.

**Comment by aeberhard** [comment]
Die beiden Addons **consent_manager** und **demo_fullpage** habe ich übrigens auch mit rexstan überarbeitet.
Und auch schon a bisserl zu rexstan und FAQ beigetragen :)
